# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 536d9fbb1e9df4fdcfe62943210eb92b8b28d578b1e9287eea7b6205d268fe544696426baecce871cc047ef2c9e8e333b075e152ae7517a8b6e3e9871528932c

test:
  secret_key_base: 631b49aca9996d14ae2f08cd98df64395598d049308e0b733ec69fce8e8a7e06f3d714f1a5b87c852f60cae99ff9131e857db523f3c96bf0cc0697c397c21fde

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
